from ._update_local_models import update_local_models
from ._partial_fit_local_A2C import partial_fit_local_A2C
from ._partial_fit_local_DQN import partial_fit_local_DQN
from ._memory_replay import memory_replay