from ._DQN import DQN
from ._handwritten_SGD import HandWrittenSGD
from ._sklearn_SGD import SklearnSGD
from ._A2C import A2C
from ._ModelsHolder import ModelsHolder
from ._memory_replay import memory_replay
from ._DuelingDQN import DuelingDQN
from ._partial_fit_A2C import partial_fit_A2C
from ._partial_fit_DQN import partial_fit_DQN